<?php

/**
 * Implements hook_views_pre_render().
 */
function coopernetnewsletter_views_pre_render($view)
{
    //dpm($view); // provoque une erreur mais je ne sais pas pourquoi
    //dpm($view->current_display);
    if ($view->current_display == "entity_reference_") {
        $events = array();
        $today = gmdate('Y-m-d\TH:i:s'); // j'ai récupéré ce format dans la vue concernée (entity_reference_newsletter)
        foreach ($view->result as $event) {
            $dates = $event->_entity->field_date->getValue();
            foreach ($dates as $date) {
                if($date['value'] > $today ) {
                    $events[$date['value']] = $event;
                }
            }
        }
        ksort($events); // Classe en fonction de la valeur de la clé
        $view->result = $events;
    } else if ($view->current_display == "entity_reference_nl_articles") {
      $articles = array();
      $cpt = 0;
      // on limite la vue à 20 résultats
      foreach ($view->result as $article) {
        if($cpt < 20) {
          $articles[] = $article;
        } else {break;}
        $cpt ++;
      }
      $view->result = $articles;
    }

}
